// アプリ全体に影響するレイアウト
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-200 p-4">
          rootヘッダー
        </header>
        {children}
      </body>
    </html>
  );
}
